//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Items')
export class ItemsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Name: string;

  @Column('text', { nullable: true })
  Picture: string;

  @Column('text', { nullable: true })
  Description: string;

  @Column('real', { nullable: true })
  Price: number;

  @Column('bool', { nullable: true })
  Favorite: boolean;

  @Column('integer', { nullable: true })
  Popularity: number;
}
