//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    Items: [
      {
        Name: 'Name 1',
        Picture: 'Picture 1',
        Description: 'Description 1',
        Price: 0.9,
        Favorite: false,
        Popularity: 1,
        id: 80,
      },
      {
        Name: 'Name 2',
        Picture: 'Picture 2',
        Description: 'Description 2',
        Price: 0.58,
        Favorite: false,
        Popularity: 2,
        id: 30,
      },
      {
        Name: 'Name 3',
        Picture: 'Picture 3',
        Description: 'Description 3',
        Price: 0.4,
        Favorite: true,
        Popularity: 3,
        id: 32,
      },
      {
        Name: 'Name 4',
        Picture: 'Picture 4',
        Description: 'Description 4',
        Price: 0.73,
        Favorite: true,
        Popularity: 4,
        id: 87,
      },
      {
        Name: 'Name 5',
        Picture: 'Picture 5',
        Description: 'Description 5',
        Price: 0.44,
        Favorite: true,
        Popularity: 5,
        id: 55,
      },
    ],
    Users: [
      { Username: 'Username 1', Password: 'Password 1', id: 99 },
      { Username: 'Username 2', Password: 'Password 2', id: 46 },
      { Username: 'Username 3', Password: 'Password 3', id: 17 },
      { Username: 'Username 4', Password: 'Password 4', id: 97 },
      { Username: 'Username 5', Password: 'Password 5', id: 71 },
    ],
  },
};
export default data;
