//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Items: {
      name: 'Items',
      fields: {
        Name: 'Name',
        Picture: 'Picture',
        Description: 'Description',
        Price: 'Price',
        Favorite: 'Favorite',
        Popularity: 'Popularity',
        id: 'id',
      },
    },
    Users: {
      name: 'Users',
      fields: { Username: 'Username', Password: 'Password', id: 'id' },
    },
  },
};
const frResources = {
  resources: {
    Items: {
      name: 'Items (fr)',
      fields: {
        Name: 'Name (fr)',
        Picture: 'Picture (fr)',
        Description: 'Description (fr)',
        Price: 'Price (fr)',
        Favorite: 'Favorite (fr)',
        Popularity: 'Popularity (fr)',
        id: 'id',
      },
    },
    Users: {
      name: 'Users (fr)',
      fields: {
        Username: 'Username (fr)',
        Password: 'Password (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
